### ISSUE TITLE
Project Creation Error

### ISSUE THREAD

**Issue by paulbonnett** [levvayner/ATF15xx-cupl#1]
Probably me being stupid, but I get the following error when I try to create a project:

> "Error running command vs-cupl.createProject: Cannot read properties of undefined (reading '0'). This is likely caused by the extension that contributes vs-cupl.createProject."

System details are:

> Version: 1.85.2
> Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
> Date: 2024-01-18T06:40:19.222Z
> Electron: 25.9.7
> ElectronBuildId: 26354273
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Linux x64 6.6.10-1-MANJARO

I ran the pre-requisites test:
 

> Running Pre-requisite checks
> Cupl.exe is OK!
> wine     is OK!
> openocd  is OK!
> minipro  is OK!
> Passed Pre-requisite checks

Any help would be appreciated

**Comment by levvayner** [comment]
Please grab v0.2.6. I think it should resolve this issue.

**Comment by paulbonnett** [comment]
Thanks for prompt reply.
According to changelog.md, v0.2.4 is latest on github, where do I find v0.2.6?

**Comment by levvayner** [comment]
You can install the extension directly from vs code's extensions module.
![image](https://github.com/levvayner/ATF15xx-cupl/assets/6651473/d93d6b2c-eda8-46a1-a738-2721be17b155)

Latest is also published to github.

**Comment by levvayner** [comment]
@paulbonnett please let me know if that resolved your issue.

**Comment by paulbonnett** [comment]
Just had chance to try it and unfortunately got the same problem.

**Comment by paulbonnett** [comment]
Thanks, VSCode already installed in described manner.  Applied update v0.2.7, can now create a project.  I will do further tests later today and report back, but so far looks good.  Thanks for you help, much appreciated.
