### ISSUE TITLE
Where to set the Minipro command options to bypass "minipro -t" to work with T48  ?

### ISSUE THREAD

**Issue by rickygai** [levvayner/ATF15xx-cupl#2]
**Microsoft Windows Version 22H2 (OS Build 22621.3880)
Visual Studio Code Version 1.91.1
VS CUPL v0.2.7
T48 (TL866-3G) programmer**

How to configure the Minipro command options under VS CUPL settings as there is no such option available aside its path setting only ?

Each time to erase or write image to ATF22V10C, the Minipro stopped at error messages output below and cannot proceed.

```
Executing Command [ C:\msys64\home\minipro\minipro -t  ] @ 7/23/2024, 6:33:38 PM
Error executing: C:\msys64\home\minipro\minipro -t 
Output:

Error Details:
Command failed: C:\msys64\home\minipro\minipro -t 
Found T48 01.1.31 (0x11f)
Warning: T48 support is experimental!
Device code: 44A13528
Serial code: 3DYY2TUJ1UP3JK1B4U4C2972
T48: hardware_check not implemented
```

However, I manually writing the image file via command line like below, it has no problem.

![image](https://github.com/user-attachments/assets/8026edd8-2fe7-4dd8-9572-cd8867847e20)

I want to know where to set the command options for Minipro in VS CUPL ?

Please advise.

**Comment by rickygai** [comment]
I believed the output of minipro -t or -V still prevent the VS CUPL to proceed the Deploy/Dump/Erase operation to T48 as I have tested it but as shown in previous result picture, by manually running the minipro on elevated command prompt, it is able to carry out the Deploy and Erase operations to T48.

In this case, I have checked the VS CUPL extension.js location under "C:\Users\RICKY GAI\.vscode\extensions\vaynersystems.vs-cupl-0.2.7\dist\extension.js" which is obfuscated, I changed the "minipro -t" to "minipro -V", it still has problem with error messages "Failed to find device by this name:" but obviously, using manually minipro command execution on command prompt has no problem as shown error messages below.

```

 @ 7/24/2024, 5:46:46 AM
** Built module ** Template successfully
Executing Command [ c:\msys64\home\rickyg~1\minipro\minipro -V  ] @ 7/24/2024, 5:47:55 AM
>> @ 7/24/2024, 5:47:56 AM
Executing Command [ c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/minipro\logicic.xml --infoic c:/msys64/home/rickyg~1/minipro\infoic.xml -L ATF22V10C ] @ 7/24/2024, 5:47:56 AM
>>ATF22V10C
ATF22V10C@SOIC24
ATF22V10C@TSSOP24
ATF22V10C(UES)
ATF22V10C(UES)@SOIC24
ATF22V10C(UES)@TSSOP24
ATF22V10CP
ATF22V10CP@SOIC24
ATF22V10CP@TSSOP24
ATF22V10CP(UES)
ATF22V10CP(UES)@SOIC24
ATF22V10CP(UES)@TSSOP24
ATF22V10CEXT
ATF22V10CEXT@SOIC24
ATF22V10CEXT@TSSOP24
ATF22V10CQ
ATF22V10CQ@SOIC24
ATF22V10CQ@TSSOP24
ATF22V10CQ(UES)
ATF22V10CQ(UES)@SOIC24
ATF22V10CQ(UES)@TSSOP24
ATF22V10CQZ
ATF22V10CQZ@SOIC24
ATF22V10CQZ@TSSOP24
ATF22V10CQZ(UES)
ATF22V10CQZ(UES)@SOIC24
ATF22V10CQZ(UES)@TSSOP24
ATF22V10CZ
ATF22V10CZ@SOIC24
ATF22V10CZ@TSSOP24
ATF22V10CZ(UES)
ATF22V10CZ(UES)@SOIC24
ATF22V10CZ(UES)@TSSOP24
 @ 7/24/2024, 5:47:56 AM
Erasing using MiniPro Template
Executing Command [ c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/miniprologicic.xml --infoic c:/msys64/home/rickyg~1/miniproinfoic.xml -p "ATF22V10C(UES)" -E  2>&1 | tee ] @ 7/24/2024, 5:48:17 AM
Error executing: c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/miniprologicic.xml --infoic c:/msys64/home/rickyg~1/miniproinfoic.xml -p "ATF22V10C(UES)" -E  2>&1 | tee
Output:

Error Details:
Command failed: c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/miniprologicic.xml --infoic c:/msys64/home/rickyg~1/miniproinfoic.xml -p "ATF22V10C(UES)" -E  2>&1 | tee
'tee' is not recognized as an internal or external command,
operable program or batch file.

 @ 7/24/2024, 5:48:17 AM:
Error occured calling minipro:Error: Command failed: c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/miniprologicic.xml --infoic c:/msys64/home/rickyg~1/miniproinfoic.xml -p "ATF22V10C(UES)" -E  2>&1 | tee
'tee' is not recognized as an internal or external command,
operable program or batch file.
 : 

```

Later, by using other CUPL VSCode plugin, I found out from internet forum that the Windows PowerShell has problem interpreting double quotes, eventually I managed to resolved the tasks.json problem and able to deploy tasks such as Writing .jed file and Erasing operation to the T48 via the use of minipro in tasks.json.

The VS CUPL Preview has problem during aligning the Chipview and Pinview panels, where the caption or title text is not showing up as shown below.

![image](https://github.com/user-attachments/assets/c54ed082-1ebf-46b7-8295-39b9c8791077)

Anyhow, may be the next version of VS CUPL will be better. Meantime, I am fine working with the CUPL Language Support
v1.0.1 plugin now.

Thanks again.

**Comment by levvayner** [comment]
Hi, could you please download version 0.2.8 and try again.
In this new release, output of the first command (that verifies presence of a programmer) is adjusted to account for the unsupported T48 hardware_check message. It also removes the `| tee` from the call on windows.

**Comment by rickygai** [comment]
Thanks, I have tested the version 0.2.8, still unable to carry out the Deploy/Dump/Erase operations to T48 as shown below.

**The error messages and suggested UI controls:**
![image](https://github.com/user-attachments/assets/41908c3a-1830-4fa7-be4d-ae064c2e13ff)

**The Deploy error messages:**
```
@ 7/25/2024, 7:45:27 AM:
Executing Command [ c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/minipro\logicic.xml --infoic c:/msys64/home/rickyg~1/minipro\infoic.xml -L ATF22V10C ] @ 7/25/2024, 7:45:27 AM
>>ATF22V10C
ATF22V10C@SOIC24
ATF22V10C@TSSOP24
ATF22V10C(UES)
ATF22V10C(UES)@SOIC24
ATF22V10C(UES)@TSSOP24
ATF22V10CP
ATF22V10CP@SOIC24
ATF22V10CP@TSSOP24
ATF22V10CP(UES)
ATF22V10CP(UES)@SOIC24
ATF22V10CP(UES)@TSSOP24
ATF22V10CEXT
ATF22V10CEXT@SOIC24
ATF22V10CEXT@TSSOP24
ATF22V10CQ
ATF22V10CQ@SOIC24
ATF22V10CQ@TSSOP24
ATF22V10CQ(UES)
ATF22V10CQ(UES)@SOIC24
ATF22V10CQ(UES)@TSSOP24
ATF22V10CQZ
ATF22V10CQZ@SOIC24
ATF22V10CQZ@TSSOP24
ATF22V10CQZ(UES)
ATF22V10CQZ(UES)@SOIC24
ATF22V10CQZ(UES)@TSSOP24
ATF22V10CZ
ATF22V10CZ@SOIC24
ATF22V10CZ@TSSOP24
ATF22V10CZ(UES)
ATF22V10CZ(UES)@SOIC24
ATF22V10CZ(UES)@TSSOP24
 @ 7/25/2024, 7:45:27 AM
Uploading using MiniPro VSCuplTest
Executing Command [ c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/miniprologicic.xml --infoic c:/msys64/home/rickyg~1/miniproinfoic.xml -p "ATF22V10C(UES)" -w "c:\DEMO\CUPL\Projects\VS_CUPL\VSCuplTest\VSCuplTest.jed"  2>&1 ] @ 7/25/2024, 7:45:32 AM
Error executing: c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/miniprologicic.xml --infoic c:/msys64/home/rickyg~1/miniproinfoic.xml -p "ATF22V10C(UES)" -w "c:\DEMO\CUPL\Projects\VS_CUPL\VSCuplTest\VSCuplTest.jed"  2>&1
Output:
c:/msys64/home/rickyg~1/miniprologicic.xml: No such file or directory
Device ATF22V10C(UES) not found!

Error Details:
Command failed: c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/miniprologicic.xml --infoic c:/msys64/home/rickyg~1/miniproinfoic.xml -p "ATF22V10C(UES)" -w "c:\DEMO\CUPL\Projects\VS_CUPL\VSCuplTest\VSCuplTest.jed"  2>&1

 @ 7/25/2024, 7:45:32 AM:c:/msys64/home/rickyg~1/miniprologicic.xml: No such file or directory
Device ATF22V10C(UES) not found!

Error occured calling minipro:Error: Command failed: c:\msys64\home\rickyg~1\minipro\minipro --logicic c:/msys64/home/rickyg~1/miniprologicic.xml --infoic c:/msys64/home/rickyg~1/miniproinfoic.xml -p "ATF22V10C(UES)" -w "c:\DEMO\CUPL\Projects\VS_CUPL\VSCuplTest\VSCuplTest.jed"  2>&1
 : c:/msys64/home/rickyg~1/miniprologicic.xml: No such file or directory
Device ATF22V10C(UES) not found!

```

**Comment by levvayner** [comment]
Hi Ricky, thank you those are great suggestions.
I reviewed output  you've provided (thank you), and found there was an issue with (1) path format for xml files and (2) erase command wasn't updated like program in v.0.2.8.

Please grab v0.3.0, that should resolve the programming and erase command issues that you have outlined above.
Regarding layout formatting for chip view, unfortunately there are issues in VS code interpreter that create unexpected results.
Regarding adding options to provide additional parameters to minipro programmer, that will be added to the backlog.
If you are included, feel free to fork this code and implement. Otherwise I can follow up with you when this feature has been added.

**Comment by rickygai** [comment]
hi, you are most welcome, well as usual, lacking time to read other codes, so much depends on you or others to update. Thanks again.

**Comment by levvayner** [comment]
Great. Did erasing and programming using minipro and T48 work for you in version 0.3.0? Or did you still have errors?

**Comment by rickygai** [comment]
hi,

Just tested the VS Cupl v0.3.0, all functions working properly now, the result is captured [HERE](https://gist.github.com/rickygai/58925c497db452284053086a05f0f4d7).

One suggestion is, again related to the Minipro manually key in parameter options because each time I have to manually specify the actual IC's name for the Minipro to recognize such as choosing "**ATF22V10C(UES)**" from the top text input upon the Deploy, Dump, Erase operations as shown below.

![image](https://github.com/user-attachments/assets/1c28f50a-b3fc-4850-941b-9b14990f1eea)

Please add in the features in the future, to allow users to key in the Minipro parameter options from the File > Preferences > Settings > User > Extensions > VS Cupl, this is very important to embedded programming because wrong voltage related option configured may ruin the IC.

Thank you.

**Comment by levvayner** [comment]
Thanks. I'll add your request to our backlog.
